### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by mirek** [pwnall/fallocate#1]
```
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in `gem_original_require': /var/lib/gems/1.8/gems/fallocate-0.1.0/lib/fallocate.rb:20: syntax error, unexpected ')', expecting '=' (SyntaxError)
/var/lib/gems/1.8/gems/fallocate-0.1.0/lib/fallocate.rb:25: syntax error, unexpected kEND, expecting $end
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:59:in `require'
    from ./fill.rb:6
```

looking at https://github.com/pwnall/fallocate/blob/master/lib/fallocate.rb#L20 it doesn't make sense to set default value for offset, which is not the last/default param.

**Comment by pwnall** [comment]
Thanks for your bug report!

Ruby 1.9 supports this, and I developed against it.

I just added Ruby 1.8 support in the 0.1.1 release, which was prompted by your bug report. Please let me know if you're still having issues with it.

Once again, thanks!
